theme = "tokyonight"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists} {liked}
{album} • {genres}
{metadata}"""
playback_metadata_fields = [
    "repeat",
    "shuffle",
    "volume",
    "device",
]
notify_timeout_in_secs = 0
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
progress_bar_position = "Bottom"
genre_num = 2
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
enable_media_control = true
enable_streaming = "Always"
enable_notify = true
enable_cover_image_cache = true
notify_streaming_only = false
seek_duration_secs = 5
sort_artist_albums_by_type = false

[notify_format]
summary = "{artists}"
body = "{track}"

[layout]
playback_window_position = "Bottom"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 70
bitrate = 320
audio_cache = false
normalization = false
autoplay = false

[[themes]]
name = "tokyonight"
[themes.palette]
background = "#1f2335"
foreground = "#c0caf5"
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#2ac3de"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#eee8d5"
bright_black = "#24283b"
bright_red = "#ff4499"
bright_green = "#73daca"
bright_yellow = "#657b83"
bright_blue = "#839496"
bright_magenta = "#ff007c"
bright_cyan = "#93a1a1"
bright_white = "#fdf6e3"

